### ISSUE TITLE
vwc doesn't implement locale support, thus, the comparison with GNU wc is incorrect

### ISSUE THREAD

**Issue by esyr** [schicho/vwc#2]
`$ /usr/bin/time -f "%es %MKB" wc enwik8`
`  1128023  13303065 100000000 enwik8`
`1.03s 1904KB`
`$ /usr/bin/time -f "%es %MKB" wc enwik8`
`  1128023  13303065 100000000 enwik8`
`0.97s 1896KB`
`$ LANG=C /usr/bin/time -f "%es %MKB" wc enwik8 `
`  1128023  13292911 100000000 enwik8`
`0.48s 1480KB`
`$ LANG=C /usr/bin/time -f "%es %MKB" wc enwik8`
`  1128023  13292911 100000000 enwik8`
`0.45s 1372KB`

**Comment by schicho** [comment]
I know.

See the second to last sentence in my conclusion.
If you read the other articles I mentioned in the introduction, you will see that all the other 'clones' are also written in the same feature-reduced way.

> Like in the other articles, this is not meant to be a V is better than C article. I wrote a very simplified version of the complete GNU wc. The only goal was to be faster, but still have the same results as GNU wc on pure ascii text.

**Comment by esyr** [comment]
That's why I see it important to perform all the comparison runs with the C locale, so the results are actually meaningful.

**Comment by schicho** [comment]
Ahh, now I see what you mean.
I didn't know about this 'locale' at first, nor did I know that it would make a difference.

Thank you for your note.
I will update the benchmark soon!

**Comment by schicho** [comment]
I updated the benchmarks.

**Comment by esyr** [comment]
Thank you; I don't have Ubuntu 20.04 at hand, but I presume, however, that memory usage has also been changed similarly to my runs.
