### ISSUE TITLE
moving to coreutils?

### ISSUE THREAD

**Issue by medvednikov** [schicho/vwc#3]
hi

we now have an official coreutils repo:

https://github.com/vlang/coreutils

would you like to move this there?

**Comment by schicho** [comment]
Oh yes, absolutely!

I was just curious if this is good enough, but according to your readme it does not require 1 to 1 parity, so this is definitely good enough.

So how can I do this?
I am not exactly sure how I can move this repository into another repository's subfolder.

Also do you want both implementations I wrote?

Or is it simpler to just copy the commits?
Anyway, please let me know what the best way forward would be.

**Comment by schicho** [comment]
Closing this, because meanwhile my code has been copied and adapted and contributed to the project.
